### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [awjdthornton/TeaCozy#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project. The site looks great and you did an excellent job keeping both the project folder and the code itself neat, organized, and readable throughout. Good use of flex display to help align items throughout the page as well!

Behind the scenes, consider using more descriptive class names for certain sections to help make your code easier to read and understand at a glance. Also, be sure to fill in the alt attribute on your img element to ensure that a wider variety of users have access to that information. 

From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Have fun and keep up the good work!

**Comment by awjdthornton** [comment]
thanks for the feedback. I've made most of the changes you suggested and associated them with the corresponding Issues. I also read the bootstrap articl
